//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by VoD.rc
//
#define IDR_MANIFEST                    1
#define IDOK2                           3
#define IDD_NAME                        9
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDD_VOD_FORM                    101
#define IDR_MENU1                       102
#define IDD_NAME1                       102
#define ID_ADD1                         103
#define IDD_NAME2                       103
#define IDD_LOGIN                       104
#define ID_ADD2                         104
#define IDD_TABPROJECT                  105
#define ID_ADD3                         105
#define ID_ADD4                         106
#define IDD_TABMANAGE                   107
#define ID_ADD5                         107
#define IDR_MENU2                       108
#define IDD_NAME3                       108
#define IDR_MENU3                       109
#define IDD_NAME4                       109
#define IDR_MENU4                       110
#define IDR_MENU5                       111
#define IDR_HTML_FACULTY                112
#define IDR_HTML_DEPARTMENT             113
#define IDR_HTML_COURSE                 114
#define IDR_HTML_CHAPTER                115
#define IDR_HTML_PROJECT                116
#define IDR_HTML_PROJECT1               121
#define IDR_HTML_FTP                    122
#define IDD_EMPTY                       123
#define IDR_MAINFRAME                   128
#define IDR_VoDTYPE                     129
#define GUIDFORMAT                      129
#define ID_LOGIN_CONNECT                130
#define ID_LOGIN_DISCONNECT             131
#define IDI_ICON1                       132
#define IDR_AVI1                        135
#define IDI_LEDON                       138
#define IDI_LEDOFF                      139
#define IDR_MENU6                       141
#define ID_MENU_EDITTHISPROJECT         142
#define IDR_DEFAULT1                    146
#define IDI_RECING                      150
#define IDI_PAUSE                       151
#define IDI_PAUSE1                      152
#define IDI_PLAY                        153
#define IDI_PLAY1                       154
#define IDI_REC                         155
#define IDI_ICON8                       156
#define IDI_RECOVER                     156
#define IDR_DATA1                       157
#define IDR_DATA2                       158
#define IDR_FORMATBAR                   163
#define IDI_STOP                        164
#define IDI_STOP1                       165
#define IDR_MENU7                       166
#define ID_ADDNEWINDICATOR_ADDINFORMATIONTOTHISPOINT 167
#define IDR_MENU8                       168
#define ID_EDITIND_EDITTHISINFORMATION  169
#define IDR_MAINFRAME1                  169
#define ID_EDITIND_DELETETHISINDICATOR  170
#define IDR_MAINFRAME2                  170
#define ID_BUILD_SENDPROJECTTOSERVER    171
#define ID_BUILD_UPLOADPROJECT          172
#define ID_BUILD_UPLOADPROJECT173       173
#define ID_BUILD_UPLOADPROJECT174       174
#define ID_BUILD_UPLOADPROJECT175       175
#define ID_TEST_TEST                    176
#define IDD_DIALOG1                     178
#define IDD_FTPUP                       178
#define IDD_NEWFTP                      179
#define IDD_FTPDOWN                     180
#define ID_BUILD_ADDFILESERVER          181
#define IDD_FTPDOWN1                    181
#define IDD_DELETE                      181
#define ID_FILE_CLOSEPROJECT            182
#define IDB_BITMAP2                     183
#define IDR_DATA3                       185
#define IDC_SLIDER1                     1000
#define IDC_TAB1                        1001
#define IDC_Name                        1001
#define IDC_BrEdit                      1002
#define IDC_BUTTON1                     1003
#define IDC_EDIT3                       1003
#define IDC_BUTTON2                     1004
#define IDC_EDIT1                       1004
#define IDC_EDIT4                       1004
#define IDC_EDIT2                       1005
#define IDC_CODE                        1005
#define IDC_FACULTY                     1005
#define IDC_EDIT5                       1005
#define IDC_Subject                     1005
#define IDC_IPADDRESS1                  1006
#define IDC_BUTTON3                     1006
#define IDC_EDIT6                       1006
#define IDC_ANIMATE1                    1007
#define IDC_BUTTON4                     1007
#define IDC_DEPARTMENT                  1007
#define IDC_TAB2                        1008
#define IDC_BUTTON5                     1008
#define IDC_TREE1                       1009
#define IDC_TREE2                       1010
#define IDC_Description                 1011
#define IDC_EDIT7                       1013
#define IDC_SCREEN                      1014
#define IDC_ANIMATE2                    1015
#define IDC_CUSTOM1                     1016
#define IDC_PROGRESS1                   1019
#define IDC_LIST1                       1020
#define IDC_COMBO2                      1022
#define IDC_COMBO3                      1023
#define IDC_EDFAC                       10010
#define ID_UNDERLINE                    32771
#define ID_ITALIC                       32772
#define ID_BOLD                         32773
#define ID_LEFT                         32774
#define ID_CENTER                       32775
#define ID_RIGHT                        32776
#define ID_BUTTON32778                  32778
#define ID_BACKCOLOR                    32779
#define ID_HYPERLINK                    32781
#define ID_ORDEREDLIST                  32783
#define ID_ORDERLIST                    32783
#define ID_INDENT                       32784
#define ID_OUTDENT                      32785
#define ID_UNORDERLIST                  32786
#define ID_BROWSE                       32788
#define ID_IMAGE                        32790
#define ID_FONT                         32793

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        186
#define _APS_NEXT_COMMAND_VALUE         32780
#define _APS_NEXT_CONTROL_VALUE         1024
#define _APS_NEXT_SYMED_VALUE           124
#endif
#endif
