// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "explorer2.h"

/////////////////////////////////////////////////////////////////////////////
// CExplorer2

IMPLEMENT_DYNCREATE(CExplorer2, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CExplorer2 properties

/////////////////////////////////////////////////////////////////////////////
// CExplorer2 operations
