// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "explorer3.h"

/////////////////////////////////////////////////////////////////////////////
// CExplorer3

IMPLEMENT_DYNCREATE(CExplorer3, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CExplorer3 properties

/////////////////////////////////////////////////////////////////////////////
// CExplorer3 operations
